### ISSUE TITLE
Neither old nor new version of pydicom seems to be supported in current version of dicomutils.

### ISSUE THREAD

**Issue by Matthew-Jennings** [raysearchlabs/dicomutils#8]
`builders.py` contains `import pydicom as dicom`, which is inconsistent with `pydicom < 1.0`, but
`build_dicom.py` contains `import dicom`, which is inconsistent with `pydicom > 1.0`

**Comment by SimonBiggs** [comment]
Do you have trouble with the following version:

https://github.com/raysearchlabs/dicomutils/tree/97fbcdb0ff85da419c22b76078857030cbc4c141

**Comment by Matthew-Jennings** [comment]
Yes, but a different error:

```bash
λ python build_dicom.py --patient-position HFS --values 0 --voxelsize 5,5,5 --voxels 100,100,100 --modality CT --structure external --modality RTSTRUCT
Traceback (most recent call last):
  File "build_dicom.py", line 88, in <module>
    ib = sb.build_ct(num_voxels=num_voxels, voxel_size=voxel_size, center=np.array(series.center))
  File "C:\Users\mjenni03\PythonProjects\RS_dicomutils\builders.py", line 93, in build_ct
    b = CTBuilder(self.current_study, num_voxels, voxel_size, center=center, rescale_slope=rescale_slope, rescale_intercept=rescale_intercept, column_direction=column_direction, row_direction=row_direction, slice_direction=slice_direction)
  File "C:\Users\mjenni03\PythonProjects\RS_dicomutils\builders.py", line 159, in __init__
    if center == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
